project:
  type: website
  output-dir: docs
  
  
website:
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    center: "Marc Thévenin - Ined-Sms - Août 2022" 
    background: light
  navbar:
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/mthevenin 
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
        
        
format:
  html:
    theme:  vapor       
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    highlight-style: monochrome        